import { type DbSeedFn } from "wasp/server"

export const seedPlants: DbSeedFn = async (prisma) => {
  // Remove previously seeded plants that the user hasn't customized
  await prisma.plant.deleteMany({
    where: { dataSource: "SEED", isUserEdited: false },
  })

  const plants = [
    // ═══════════════════════════════════════════════
    // VEGETABLES (~40)
    // ═══════════════════════════════════════════════

    // --- Tomatoes ---
    {
      name: "Tomato",
      scientificName: "Solanum lycopersicum",
      variety: "Early Girl",
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "WARM",
      daysToMaturity: 57,
      daysToGermination: 7,
      spacingInches: 24,
      plantHeightInches: 48,
      startIndoorWeeks: -8,
      transplantWeeks: 1,
      directSowWeeks: null,
      harvestRelativeWeeks: 10,
      plantsPerSqFt: 1,
      sqftColor: "#E53935",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Tomato",
      scientificName: "Solanum lycopersicum",
      variety: "Roma",
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "WARM",
      daysToMaturity: 75,
      daysToGermination: 7,
      spacingInches: 24,
      plantHeightInches: 36,
      startIndoorWeeks: -8,
      transplantWeeks: 1,
      directSowWeeks: null,
      harvestRelativeWeeks: 12,
      plantsPerSqFt: 1,
      sqftColor: "#C62828",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Tomato",
      scientificName: "Solanum lycopersicum",
      variety: "Cherry (Sungold)",
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "WARM",
      daysToMaturity: 60,
      daysToGermination: 7,
      spacingInches: 18,
      plantHeightInches: 60,
      startIndoorWeeks: -8,
      transplantWeeks: 1,
      directSowWeeks: null,
      harvestRelativeWeeks: 10,
      plantsPerSqFt: 1,
      sqftColor: "#EF5350",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },

    // --- Peppers ---
    {
      name: "Pepper",
      scientificName: "Capsicum annuum",
      variety: "Bell",
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "WARM",
      daysToMaturity: 70,
      daysToGermination: 10,
      spacingInches: 18,
      plantHeightInches: 24,
      startIndoorWeeks: -10,
      transplantWeeks: 2,
      directSowWeeks: null,
      harvestRelativeWeeks: 12,
      plantsPerSqFt: 1,
      sqftColor: "#FF9800",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Pepper",
      scientificName: "Capsicum annuum",
      variety: "Jalape\u00f1o",
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "WARM",
      daysToMaturity: 72,
      daysToGermination: 10,
      spacingInches: 15,
      plantHeightInches: 24,
      startIndoorWeeks: -10,
      transplantWeeks: 2,
      directSowWeeks: null,
      harvestRelativeWeeks: 12,
      plantsPerSqFt: 1,
      sqftColor: "#F57C00",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },

    // --- Cucurbits ---
    {
      name: "Cucumber",
      scientificName: "Cucumis sativus",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "HIGH",
      seasonType: "WARM",
      daysToMaturity: 58,
      daysToGermination: 7,
      spacingInches: 12,
      plantHeightInches: 12,
      startIndoorWeeks: -4,
      transplantWeeks: 1,
      directSowWeeks: 1,
      harvestRelativeWeeks: 9,
      plantsPerSqFt: 2,
      sqftColor: "#558B2F",
      permLayer: "VINE",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Zucchini",
      scientificName: "Cucurbita pepo",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "WARM",
      daysToMaturity: 50,
      daysToGermination: 7,
      spacingInches: 24,
      plantHeightInches: 24,
      startIndoorWeeks: -3,
      transplantWeeks: 1,
      directSowWeeks: 1,
      harvestRelativeWeeks: 8,
      plantsPerSqFt: 1,
      sqftColor: "#689F38",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Summer Squash",
      scientificName: "Cucurbita pepo",
      variety: "Yellow Crookneck",
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "WARM",
      daysToMaturity: 55,
      daysToGermination: 7,
      spacingInches: 24,
      plantHeightInches: 24,
      startIndoorWeeks: -3,
      transplantWeeks: 1,
      directSowWeeks: 1,
      harvestRelativeWeeks: 9,
      plantsPerSqFt: 1,
      sqftColor: "#9E9D24",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Winter Squash",
      scientificName: "Cucurbita moschata",
      variety: "Butternut",
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "WARM",
      daysToMaturity: 100,
      daysToGermination: 7,
      spacingInches: 36,
      plantHeightInches: 18,
      startIndoorWeeks: -4,
      transplantWeeks: 1,
      directSowWeeks: 1,
      harvestRelativeWeeks: 16,
      plantsPerSqFt: 1,
      sqftColor: "#BF8040",
      permLayer: "VINE",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Winter Squash",
      scientificName: "Cucurbita pepo",
      variety: "Acorn",
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "WARM",
      daysToMaturity: 85,
      daysToGermination: 7,
      spacingInches: 36,
      plantHeightInches: 18,
      startIndoorWeeks: -4,
      transplantWeeks: 1,
      directSowWeeks: 1,
      harvestRelativeWeeks: 14,
      plantsPerSqFt: 1,
      sqftColor: "#A0522D",
      permLayer: "VINE",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Pumpkin",
      scientificName: "Cucurbita pepo",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "WARM",
      daysToMaturity: 100,
      daysToGermination: 7,
      spacingInches: 48,
      plantHeightInches: 18,
      startIndoorWeeks: -3,
      transplantWeeks: 1,
      directSowWeeks: 1,
      harvestRelativeWeeks: 16,
      plantsPerSqFt: 1,
      sqftColor: "#E65100",
      permLayer: "VINE",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },

    // --- Legumes ---
    {
      name: "Peas",
      scientificName: "Pisum sativum",
      variety: "Snow",
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 60,
      daysToGermination: 10,
      spacingInches: 3,
      plantHeightInches: 36,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -4,
      harvestRelativeWeeks: 6,
      plantsPerSqFt: 8,
      sqftColor: "#81C784",
      permLayer: "VINE",
      isNitrogenFixer: true,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Peas",
      scientificName: "Pisum sativum",
      variety: "Snap",
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 65,
      daysToGermination: 10,
      spacingInches: 3,
      plantHeightInches: 48,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -4,
      harvestRelativeWeeks: 7,
      plantsPerSqFt: 8,
      sqftColor: "#66BB6A",
      permLayer: "VINE",
      isNitrogenFixer: true,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Peas",
      scientificName: "Pisum sativum",
      variety: "Shell",
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 70,
      daysToGermination: 10,
      spacingInches: 3,
      plantHeightInches: 30,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -4,
      harvestRelativeWeeks: 7,
      plantsPerSqFt: 8,
      sqftColor: "#4CAF50",
      permLayer: "VINE",
      isNitrogenFixer: true,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Beans",
      scientificName: "Phaseolus vulgaris",
      variety: "Bush",
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "WARM",
      daysToMaturity: 55,
      daysToGermination: 8,
      spacingInches: 4,
      plantHeightInches: 18,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: 1,
      harvestRelativeWeeks: 9,
      plantsPerSqFt: 9,
      sqftColor: "#43A047",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: true,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Beans",
      scientificName: "Phaseolus vulgaris",
      variety: "Pole",
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "WARM",
      daysToMaturity: 65,
      daysToGermination: 8,
      spacingInches: 6,
      plantHeightInches: 72,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: 1,
      harvestRelativeWeeks: 10,
      plantsPerSqFt: 8,
      sqftColor: "#2E7D32",
      permLayer: "VINE",
      isNitrogenFixer: true,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },

    // --- Corn ---
    {
      name: "Corn",
      scientificName: "Zea mays",
      variety: "Sweet",
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "HIGH",
      seasonType: "WARM",
      daysToMaturity: 75,
      daysToGermination: 7,
      spacingInches: 12,
      plantHeightInches: 72,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: 1,
      harvestRelativeWeeks: 12,
      plantsPerSqFt: 1,
      sqftColor: "#FDD835",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },

    // --- Root Vegetables ---
    {
      name: "Potato",
      scientificName: "Solanum tuberosum",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 80,
      daysToGermination: 14,
      spacingInches: 12,
      plantHeightInches: 24,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -2,
      harvestRelativeWeeks: 12,
      plantsPerSqFt: 1,
      sqftColor: "#8D6E63",
      permLayer: "ROOT",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Beet",
      scientificName: "Beta vulgaris",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 55,
      daysToGermination: 10,
      spacingInches: 4,
      plantHeightInches: 12,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -4,
      harvestRelativeWeeks: 5,
      plantsPerSqFt: 9,
      sqftColor: "#880E4F",
      permLayer: "ROOT",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Carrot",
      scientificName: "Daucus carota",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "BIENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 70,
      daysToGermination: 14,
      spacingInches: 3,
      plantHeightInches: 12,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -4,
      harvestRelativeWeeks: 7,
      plantsPerSqFt: 16,
      sqftColor: "#E65100",
      permLayer: "ROOT",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Radish",
      scientificName: "Raphanus sativus",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 25,
      daysToGermination: 4,
      spacingInches: 2,
      plantHeightInches: 6,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -6,
      harvestRelativeWeeks: -2,
      plantsPerSqFt: 16,
      sqftColor: "#D81B60",
      permLayer: "ROOT",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Turnip",
      scientificName: "Brassica rapa",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 55,
      daysToGermination: 7,
      spacingInches: 4,
      plantHeightInches: 12,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -4,
      harvestRelativeWeeks: 5,
      plantsPerSqFt: 9,
      sqftColor: "#CE93D8",
      permLayer: "ROOT",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Parsnip",
      scientificName: "Pastinaca sativa",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "BIENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 105,
      daysToGermination: 18,
      spacingInches: 4,
      plantHeightInches: 12,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -4,
      harvestRelativeWeeks: 12,
      plantsPerSqFt: 9,
      sqftColor: "#D7CCC8",
      permLayer: "ROOT",
      isNitrogenFixer: false,
      isDynamicAccumulator: true,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Rutabaga",
      scientificName: "Brassica napus",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "BIENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 90,
      daysToGermination: 7,
      spacingInches: 6,
      plantHeightInches: 14,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -4,
      harvestRelativeWeeks: 10,
      plantsPerSqFt: 4,
      sqftColor: "#BCAAA4",
      permLayer: "ROOT",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },

    // --- Alliums ---
    {
      name: "Onion",
      scientificName: "Allium cepa",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "BIENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 100,
      daysToGermination: 10,
      spacingInches: 4,
      plantHeightInches: 18,
      startIndoorWeeks: -12,
      transplantWeeks: -2,
      directSowWeeks: null,
      harvestRelativeWeeks: 14,
      plantsPerSqFt: 9,
      sqftColor: "#FFCC80",
      permLayer: "ROOT",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Garlic",
      scientificName: "Allium sativum",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "PERENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "COOL",
      daysToMaturity: 240,
      daysToGermination: 14,
      spacingInches: 6,
      plantHeightInches: 18,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -4,
      harvestRelativeWeeks: 8,
      plantsPerSqFt: 4,
      sqftColor: "#FFF9C4",
      permLayer: "ROOT",
      isNitrogenFixer: false,
      isDynamicAccumulator: true,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },

    // --- Leafy Greens ---
    {
      name: "Lettuce",
      scientificName: "Lactuca sativa",
      variety: "Leaf",
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "PARTIAL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 45,
      daysToGermination: 7,
      spacingInches: 6,
      plantHeightInches: 10,
      startIndoorWeeks: -6,
      transplantWeeks: -2,
      directSowWeeks: -4,
      harvestRelativeWeeks: 3,
      plantsPerSqFt: 4,
      sqftColor: "#AED581",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Lettuce",
      scientificName: "Lactuca sativa",
      variety: "Romaine",
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "PARTIAL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 60,
      daysToGermination: 7,
      spacingInches: 8,
      plantHeightInches: 12,
      startIndoorWeeks: -6,
      transplantWeeks: -2,
      directSowWeeks: -4,
      harvestRelativeWeeks: 5,
      plantsPerSqFt: 4,
      sqftColor: "#9CCC65",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Lettuce",
      scientificName: "Lactuca sativa",
      variety: "Head (Iceberg)",
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "PARTIAL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 70,
      daysToGermination: 7,
      spacingInches: 12,
      plantHeightInches: 10,
      startIndoorWeeks: -6,
      transplantWeeks: -2,
      directSowWeeks: -4,
      harvestRelativeWeeks: 6,
      plantsPerSqFt: 1,
      sqftColor: "#C5E1A5",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Spinach",
      scientificName: "Spinacia oleracea",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "PARTIAL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 40,
      daysToGermination: 7,
      spacingInches: 4,
      plantHeightInches: 8,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -6,
      harvestRelativeWeeks: 0,
      plantsPerSqFt: 9,
      sqftColor: "#388E3C",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Kale",
      scientificName: "Brassica oleracea var. sabellica",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "BIENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 55,
      daysToGermination: 7,
      spacingInches: 12,
      plantHeightInches: 24,
      startIndoorWeeks: -6,
      transplantWeeks: -2,
      directSowWeeks: -4,
      harvestRelativeWeeks: 4,
      plantsPerSqFt: 1,
      sqftColor: "#1B5E20",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Swiss Chard",
      scientificName: "Beta vulgaris subsp. vulgaris",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "BIENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 55,
      daysToGermination: 7,
      spacingInches: 6,
      plantHeightInches: 18,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -2,
      harvestRelativeWeeks: 6,
      plantsPerSqFt: 4,
      sqftColor: "#E91E63",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },

    // --- Brassicas ---
    {
      name: "Broccoli",
      scientificName: "Brassica oleracea var. italica",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 65,
      daysToGermination: 7,
      spacingInches: 18,
      plantHeightInches: 24,
      startIndoorWeeks: -6,
      transplantWeeks: -2,
      directSowWeeks: null,
      harvestRelativeWeeks: 8,
      plantsPerSqFt: 1,
      sqftColor: "#2E7D32",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Cauliflower",
      scientificName: "Brassica oleracea var. botrytis",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 70,
      daysToGermination: 7,
      spacingInches: 18,
      plantHeightInches: 20,
      startIndoorWeeks: -6,
      transplantWeeks: -2,
      directSowWeeks: null,
      harvestRelativeWeeks: 9,
      plantsPerSqFt: 1,
      sqftColor: "#F5F5DC",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Cabbage",
      scientificName: "Brassica oleracea var. capitata",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "BIENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 70,
      daysToGermination: 7,
      spacingInches: 18,
      plantHeightInches: 14,
      startIndoorWeeks: -6,
      transplantWeeks: -2,
      directSowWeeks: null,
      harvestRelativeWeeks: 9,
      plantsPerSqFt: 1,
      sqftColor: "#7CB342",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Brussels Sprouts",
      scientificName: "Brassica oleracea var. gemmifera",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "BIENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 100,
      daysToGermination: 7,
      spacingInches: 18,
      plantHeightInches: 30,
      startIndoorWeeks: -6,
      transplantWeeks: -2,
      directSowWeeks: null,
      harvestRelativeWeeks: 14,
      plantsPerSqFt: 1,
      sqftColor: "#33691E",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Kohlrabi",
      scientificName: "Brassica oleracea var. gongylodes",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "BIENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 55,
      daysToGermination: 7,
      spacingInches: 6,
      plantHeightInches: 12,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -4,
      harvestRelativeWeeks: 5,
      plantsPerSqFt: 4,
      sqftColor: "#B2DFDB",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },

    // --- Other Vegetables ---
    {
      name: "Celery",
      scientificName: "Apium graveolens",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "BIENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "HIGH",
      seasonType: "COOL",
      daysToMaturity: 120,
      daysToGermination: 14,
      spacingInches: 8,
      plantHeightInches: 18,
      startIndoorWeeks: -10,
      transplantWeeks: 0,
      directSowWeeks: null,
      harvestRelativeWeeks: 16,
      plantsPerSqFt: 4,
      sqftColor: "#A5D6A7",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Eggplant",
      scientificName: "Solanum melongena",
      variety: null,
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "WARM",
      daysToMaturity: 70,
      daysToGermination: 10,
      spacingInches: 18,
      plantHeightInches: 24,
      startIndoorWeeks: -8,
      transplantWeeks: 2,
      directSowWeeks: null,
      harvestRelativeWeeks: 12,
      plantsPerSqFt: 1,
      sqftColor: "#4A148C",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Melon",
      scientificName: "Cucumis melo",
      variety: "Cantaloupe",
      category: "VEGETABLE",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "HIGH",
      seasonType: "WARM",
      daysToMaturity: 85,
      daysToGermination: 7,
      spacingInches: 24,
      plantHeightInches: 12,
      startIndoorWeeks: -4,
      transplantWeeks: 2,
      directSowWeeks: null,
      harvestRelativeWeeks: 14,
      plantsPerSqFt: 1,
      sqftColor: "#FFAB91",
      permLayer: "VINE",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },

    // ═══════════════════════════════════════════════
    // HERBS (~15)
    // ═══════════════════════════════════════════════

    {
      name: "Basil",
      scientificName: "Ocimum basilicum",
      variety: null,
      category: "HERB",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "WARM",
      daysToMaturity: 60,
      daysToGermination: 7,
      spacingInches: 6,
      plantHeightInches: 18,
      startIndoorWeeks: -6,
      transplantWeeks: 1,
      directSowWeeks: null,
      harvestRelativeWeeks: 8,
      plantsPerSqFt: 4,
      sqftColor: "#66BB6A",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Cilantro",
      scientificName: "Coriandrum sativum",
      variety: null,
      category: "HERB",
      lifecycle: "ANNUAL",
      sunRequirement: "PARTIAL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 45,
      daysToGermination: 10,
      spacingInches: 4,
      plantHeightInches: 18,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -4,
      harvestRelativeWeeks: 3,
      plantsPerSqFt: 9,
      sqftColor: "#81C784",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Dill",
      scientificName: "Anethum graveolens",
      variety: null,
      category: "HERB",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 50,
      daysToGermination: 10,
      spacingInches: 6,
      plantHeightInches: 36,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -2,
      harvestRelativeWeeks: 5,
      plantsPerSqFt: 4,
      sqftColor: "#A5D6A7",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Parsley",
      scientificName: "Petroselinum crispum",
      variety: null,
      category: "HERB",
      lifecycle: "BIENNIAL",
      sunRequirement: "PARTIAL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 70,
      daysToGermination: 21,
      spacingInches: 4,
      plantHeightInches: 12,
      startIndoorWeeks: -8,
      transplantWeeks: -2,
      directSowWeeks: -4,
      harvestRelativeWeeks: 6,
      plantsPerSqFt: 9,
      sqftColor: "#4CAF50",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: true,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Chives",
      scientificName: "Allium schoenoprasum",
      variety: null,
      category: "HERB",
      lifecycle: "PERENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "COOL",
      daysToMaturity: 60,
      daysToGermination: 14,
      spacingInches: 4,
      plantHeightInches: 12,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -4,
      harvestRelativeWeeks: 5,
      plantsPerSqFt: 16,
      sqftColor: "#C8E6C9",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Oregano",
      scientificName: "Origanum vulgare",
      variety: null,
      category: "HERB",
      lifecycle: "PERENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "WARM",
      daysToMaturity: 80,
      daysToGermination: 10,
      spacingInches: 8,
      plantHeightInches: 18,
      startIndoorWeeks: -8,
      transplantWeeks: 0,
      directSowWeeks: null,
      harvestRelativeWeeks: 10,
      plantsPerSqFt: 1,
      sqftColor: "#7CB342",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Thyme",
      scientificName: "Thymus vulgaris",
      variety: null,
      category: "HERB",
      lifecycle: "PERENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "WARM",
      daysToMaturity: 90,
      daysToGermination: 14,
      spacingInches: 6,
      plantHeightInches: 12,
      startIndoorWeeks: -8,
      transplantWeeks: 0,
      directSowWeeks: null,
      harvestRelativeWeeks: 10,
      plantsPerSqFt: 4,
      sqftColor: "#8BC34A",
      permLayer: "GROUND_COVER",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Sage",
      scientificName: "Salvia officinalis",
      variety: null,
      category: "HERB",
      lifecycle: "PERENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "WARM",
      daysToMaturity: 75,
      daysToGermination: 14,
      spacingInches: 12,
      plantHeightInches: 24,
      startIndoorWeeks: -8,
      transplantWeeks: 0,
      directSowWeeks: null,
      harvestRelativeWeeks: 10,
      plantsPerSqFt: 1,
      sqftColor: "#78909C",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      isMedicinal: true,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Rosemary",
      scientificName: "Salvia rosmarinus",
      variety: null,
      category: "HERB",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "WARM",
      daysToMaturity: 80,
      daysToGermination: 21,
      spacingInches: 12,
      plantHeightInches: 24,
      startIndoorWeeks: -10,
      transplantWeeks: 1,
      directSowWeeks: null,
      harvestRelativeWeeks: 12,
      plantsPerSqFt: 1,
      sqftColor: "#546E7A",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      isMedicinal: true,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Mint",
      scientificName: "Mentha spicata",
      variety: null,
      category: "HERB",
      lifecycle: "PERENNIAL",
      sunRequirement: "PARTIAL_SUN",
      waterNeed: "HIGH",
      seasonType: "COOL",
      daysToMaturity: 70,
      daysToGermination: 12,
      spacingInches: 12,
      plantHeightInches: 18,
      startIndoorWeeks: -8,
      transplantWeeks: 0,
      directSowWeeks: null,
      harvestRelativeWeeks: 8,
      plantsPerSqFt: 1,
      sqftColor: "#26A69A",
      permLayer: "GROUND_COVER",
      isNitrogenFixer: false,
      isDynamicAccumulator: true,
      isEdible: true,
      isMedicinal: true,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Lemon Balm",
      scientificName: "Melissa officinalis",
      variety: null,
      category: "HERB",
      lifecycle: "PERENNIAL",
      sunRequirement: "PARTIAL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 70,
      daysToGermination: 14,
      spacingInches: 12,
      plantHeightInches: 24,
      startIndoorWeeks: -8,
      transplantWeeks: 0,
      directSowWeeks: null,
      harvestRelativeWeeks: 8,
      plantsPerSqFt: 1,
      sqftColor: "#80CBC4",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      isMedicinal: true,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Lavender",
      scientificName: "Lavandula angustifolia",
      variety: null,
      category: "HERB",
      lifecycle: "PERENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "WARM",
      daysToMaturity: 90,
      daysToGermination: 21,
      spacingInches: 12,
      plantHeightInches: 18,
      startIndoorWeeks: -10,
      transplantWeeks: 1,
      directSowWeeks: null,
      harvestRelativeWeeks: 12,
      plantsPerSqFt: 1,
      sqftColor: "#9575CD",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      isMedicinal: true,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Tarragon",
      scientificName: "Artemisia dracunculus",
      variety: "French",
      category: "HERB",
      lifecycle: "PERENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "WARM",
      daysToMaturity: 60,
      daysToGermination: 14,
      spacingInches: 12,
      plantHeightInches: 24,
      startIndoorWeeks: -8,
      transplantWeeks: 0,
      directSowWeeks: null,
      harvestRelativeWeeks: 8,
      plantsPerSqFt: 1,
      sqftColor: "#A5D6A7",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Chamomile",
      scientificName: "Matricaria chamomilla",
      variety: null,
      category: "HERB",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "COOL",
      daysToMaturity: 60,
      daysToGermination: 10,
      spacingInches: 6,
      plantHeightInches: 18,
      startIndoorWeeks: -6,
      transplantWeeks: 0,
      directSowWeeks: -2,
      harvestRelativeWeeks: 8,
      plantsPerSqFt: 4,
      sqftColor: "#FFF59D",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: true,
      isEdible: true,
      isMedicinal: true,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Fennel",
      scientificName: "Foeniculum vulgare",
      variety: null,
      category: "HERB",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "WARM",
      daysToMaturity: 65,
      daysToGermination: 10,
      spacingInches: 6,
      plantHeightInches: 36,
      startIndoorWeeks: -4,
      transplantWeeks: 1,
      directSowWeeks: 1,
      harvestRelativeWeeks: 10,
      plantsPerSqFt: 4,
      sqftColor: "#DCE775",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: true,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },

    // ═══════════════════════════════════════════════
    // FRUITS (~10)
    // ═══════════════════════════════════════════════

    {
      name: "Strawberry",
      scientificName: "Fragaria x ananassa",
      variety: null,
      category: "FRUIT",
      lifecycle: "PERENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 60,
      daysToGermination: 21,
      spacingInches: 12,
      plantHeightInches: 8,
      startIndoorWeeks: null,
      transplantWeeks: -2,
      directSowWeeks: null,
      harvestRelativeWeeks: 8,
      plantsPerSqFt: 4,
      sqftColor: "#E91E63",
      permLayer: "GROUND_COVER",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Raspberry",
      scientificName: "Rubus idaeus",
      variety: null,
      category: "FRUIT",
      lifecycle: "PERENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 365,
      daysToGermination: null,
      spacingInches: 24,
      plantHeightInches: 60,
      startIndoorWeeks: null,
      transplantWeeks: -2,
      directSowWeeks: null,
      harvestRelativeWeeks: 10,
      plantsPerSqFt: 1,
      sqftColor: "#C2185B",
      permLayer: "SHRUB",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Saskatoon Berry",
      scientificName: "Amelanchier alnifolia",
      variety: null,
      category: "FRUIT",
      lifecycle: "PERENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "COOL",
      daysToMaturity: 730,
      daysToGermination: null,
      spacingInches: 96,
      plantHeightInches: 144,
      startIndoorWeeks: null,
      transplantWeeks: -2,
      directSowWeeks: null,
      harvestRelativeWeeks: 8,
      plantsPerSqFt: 1,
      sqftColor: "#6A1B9A",
      permLayer: "SHRUB",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Rhubarb",
      scientificName: "Rheum rhabarbarum",
      variety: null,
      category: "FRUIT",
      lifecycle: "PERENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 365,
      daysToGermination: null,
      spacingInches: 36,
      plantHeightInches: 36,
      startIndoorWeeks: null,
      transplantWeeks: -2,
      directSowWeeks: null,
      harvestRelativeWeeks: 4,
      plantsPerSqFt: 1,
      sqftColor: "#AD1457",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: true,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Currant",
      scientificName: "Ribes rubrum",
      variety: "Red",
      category: "FRUIT",
      lifecycle: "PERENNIAL",
      sunRequirement: "PARTIAL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 365,
      daysToGermination: null,
      spacingInches: 48,
      plantHeightInches: 48,
      startIndoorWeeks: null,
      transplantWeeks: -2,
      directSowWeeks: null,
      harvestRelativeWeeks: 8,
      plantsPerSqFt: 1,
      sqftColor: "#D32F2F",
      permLayer: "SHRUB",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Currant",
      scientificName: "Ribes nigrum",
      variety: "Black",
      category: "FRUIT",
      lifecycle: "PERENNIAL",
      sunRequirement: "PARTIAL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 365,
      daysToGermination: null,
      spacingInches: 48,
      plantHeightInches: 60,
      startIndoorWeeks: null,
      transplantWeeks: -2,
      directSowWeeks: null,
      harvestRelativeWeeks: 8,
      plantsPerSqFt: 1,
      sqftColor: "#311B92",
      permLayer: "SHRUB",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Gooseberry",
      scientificName: "Ribes uva-crispa",
      variety: null,
      category: "FRUIT",
      lifecycle: "PERENNIAL",
      sunRequirement: "PARTIAL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 365,
      daysToGermination: null,
      spacingInches: 48,
      plantHeightInches: 48,
      startIndoorWeeks: null,
      transplantWeeks: -2,
      directSowWeeks: null,
      harvestRelativeWeeks: 9,
      plantsPerSqFt: 1,
      sqftColor: "#7B1FA2",
      permLayer: "SHRUB",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Haskap",
      scientificName: "Lonicera caerulea",
      variety: "Honeyberry",
      category: "FRUIT",
      lifecycle: "PERENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 365,
      daysToGermination: null,
      spacingInches: 60,
      plantHeightInches: 72,
      startIndoorWeeks: null,
      transplantWeeks: -2,
      directSowWeeks: null,
      harvestRelativeWeeks: 6,
      plantsPerSqFt: 1,
      sqftColor: "#283593",
      permLayer: "SHRUB",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Chokecherry",
      scientificName: "Prunus virginiana",
      variety: null,
      category: "FRUIT",
      lifecycle: "PERENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "COOL",
      daysToMaturity: 730,
      daysToGermination: null,
      spacingInches: 144,
      plantHeightInches: 240,
      startIndoorWeeks: null,
      transplantWeeks: -2,
      directSowWeeks: null,
      harvestRelativeWeeks: 12,
      plantsPerSqFt: 1,
      sqftColor: "#4A148C",
      permLayer: "UNDERSTORY",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Sour Cherry",
      scientificName: "Prunus cerasus",
      variety: "Evans",
      category: "FRUIT",
      lifecycle: "PERENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 730,
      daysToGermination: null,
      spacingInches: 144,
      plantHeightInches: 168,
      startIndoorWeeks: null,
      transplantWeeks: -2,
      directSowWeeks: null,
      harvestRelativeWeeks: 10,
      plantsPerSqFt: 1,
      sqftColor: "#B71C1C",
      permLayer: "UNDERSTORY",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Sour Cherry",
      scientificName: "Prunus cerasus",
      variety: "Carmine Jewel",
      category: "FRUIT",
      lifecycle: "PERENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 730,
      daysToGermination: null,
      spacingInches: 96,
      plantHeightInches: 84,
      startIndoorWeeks: null,
      transplantWeeks: -2,
      directSowWeeks: null,
      harvestRelativeWeeks: 10,
      plantsPerSqFt: 1,
      sqftColor: "#D50000",
      permLayer: "SHRUB",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },

    // ═══════════════════════════════════════════════
    // FLOWERS (~10)
    // ═══════════════════════════════════════════════

    {
      name: "Sunflower",
      scientificName: "Helianthus annuus",
      variety: null,
      category: "FLOWER",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "WARM",
      daysToMaturity: 80,
      daysToGermination: 7,
      spacingInches: 12,
      plantHeightInches: 72,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: 0,
      harvestRelativeWeeks: 12,
      plantsPerSqFt: 1,
      sqftColor: "#FFD600",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: true,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Marigold",
      scientificName: "Tagetes erecta",
      variety: null,
      category: "FLOWER",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "WARM",
      daysToMaturity: 50,
      daysToGermination: 7,
      spacingInches: 8,
      plantHeightInches: 12,
      startIndoorWeeks: -6,
      transplantWeeks: 0,
      directSowWeeks: 1,
      harvestRelativeWeeks: 8,
      plantsPerSqFt: 4,
      sqftColor: "#FF6F00",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Nasturtium",
      scientificName: "Tropaeolum majus",
      variety: null,
      category: "FLOWER",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "WARM",
      daysToMaturity: 55,
      daysToGermination: 10,
      spacingInches: 12,
      plantHeightInches: 12,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: 0,
      harvestRelativeWeeks: 8,
      plantsPerSqFt: 1,
      sqftColor: "#FF3D00",
      permLayer: "GROUND_COVER",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Zinnia",
      scientificName: "Zinnia elegans",
      variety: null,
      category: "FLOWER",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "WARM",
      daysToMaturity: 60,
      daysToGermination: 7,
      spacingInches: 6,
      plantHeightInches: 30,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: 1,
      harvestRelativeWeeks: 9,
      plantsPerSqFt: 4,
      sqftColor: "#F50057",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: false,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Cosmos",
      scientificName: "Cosmos bipinnatus",
      variety: null,
      category: "FLOWER",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "WARM",
      daysToMaturity: 60,
      daysToGermination: 7,
      spacingInches: 12,
      plantHeightInches: 48,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: 0,
      harvestRelativeWeeks: 9,
      plantsPerSqFt: 1,
      sqftColor: "#FF80AB",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: false,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Calendula",
      scientificName: "Calendula officinalis",
      variety: null,
      category: "FLOWER",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 50,
      daysToGermination: 7,
      spacingInches: 8,
      plantHeightInches: 18,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -2,
      harvestRelativeWeeks: 6,
      plantsPerSqFt: 4,
      sqftColor: "#FFB300",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      isMedicinal: true,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Echinacea",
      scientificName: "Echinacea purpurea",
      variety: null,
      category: "FLOWER",
      lifecycle: "PERENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "WARM",
      daysToMaturity: 120,
      daysToGermination: 14,
      spacingInches: 12,
      plantHeightInches: 36,
      startIndoorWeeks: -8,
      transplantWeeks: 0,
      directSowWeeks: null,
      harvestRelativeWeeks: 14,
      plantsPerSqFt: 1,
      sqftColor: "#AB47BC",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: false,
      isMedicinal: true,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Black-eyed Susan",
      scientificName: "Rudbeckia hirta",
      variety: null,
      category: "FLOWER",
      lifecycle: "PERENNIAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "WARM",
      daysToMaturity: 100,
      daysToGermination: 10,
      spacingInches: 12,
      plantHeightInches: 30,
      startIndoorWeeks: -8,
      transplantWeeks: 0,
      directSowWeeks: null,
      harvestRelativeWeeks: 14,
      plantsPerSqFt: 1,
      sqftColor: "#FFC107",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: false,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Borage",
      scientificName: "Borago officinalis",
      variety: null,
      category: "FLOWER",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 55,
      daysToGermination: 7,
      spacingInches: 12,
      plantHeightInches: 24,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -2,
      harvestRelativeWeeks: 6,
      plantsPerSqFt: 1,
      sqftColor: "#42A5F5",
      permLayer: "HERBACEOUS",
      isNitrogenFixer: false,
      isDynamicAccumulator: true,
      isEdible: true,
      isMedicinal: true,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Sweet Pea",
      scientificName: "Lathyrus odoratus",
      variety: null,
      category: "FLOWER",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "MODERATE",
      seasonType: "COOL",
      daysToMaturity: 65,
      daysToGermination: 10,
      spacingInches: 6,
      plantHeightInches: 72,
      startIndoorWeeks: -6,
      transplantWeeks: -2,
      directSowWeeks: -4,
      harvestRelativeWeeks: 8,
      plantsPerSqFt: 4,
      sqftColor: "#CE93D8",
      permLayer: "VINE",
      isNitrogenFixer: true,
      isDynamicAccumulator: false,
      isEdible: false,
      attractsPollinators: true,
      deerResistant: true,
      dataSource: "SEED",
      isUserEdited: false,
    },

    // ═══════════════════════════════════════════════
    // COVER CROPS (~5)
    // ═══════════════════════════════════════════════

    {
      name: "Crimson Clover",
      scientificName: "Trifolium incarnatum",
      variety: null,
      category: "COVER_CROP",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "COOL",
      daysToMaturity: 60,
      daysToGermination: 7,
      spacingInches: 2,
      plantHeightInches: 18,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -4,
      harvestRelativeWeeks: null,
      plantsPerSqFt: 16,
      sqftColor: "#556B2F",
      permLayer: "GROUND_COVER",
      isNitrogenFixer: true,
      isDynamicAccumulator: false,
      isEdible: false,
      attractsPollinators: true,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Winter Rye",
      scientificName: "Secale cereale",
      variety: null,
      category: "COVER_CROP",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "COOL",
      daysToMaturity: 60,
      daysToGermination: 7,
      spacingInches: 2,
      plantHeightInches: 48,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -4,
      harvestRelativeWeeks: null,
      plantsPerSqFt: 16,
      sqftColor: "#6B8E23",
      permLayer: "GROUND_COVER",
      isNitrogenFixer: false,
      isDynamicAccumulator: true,
      isEdible: false,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Buckwheat",
      scientificName: "Fagopyrum esculentum",
      variety: null,
      category: "COVER_CROP",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "WARM",
      daysToMaturity: 35,
      daysToGermination: 5,
      spacingInches: 2,
      plantHeightInches: 30,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: 2,
      harvestRelativeWeeks: null,
      plantsPerSqFt: 16,
      sqftColor: "#808000",
      permLayer: "GROUND_COVER",
      isNitrogenFixer: false,
      isDynamicAccumulator: true,
      isEdible: true,
      attractsPollinators: true,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Hairy Vetch",
      scientificName: "Vicia villosa",
      variety: null,
      category: "COVER_CROP",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "COOL",
      daysToMaturity: 70,
      daysToGermination: 10,
      spacingInches: 2,
      plantHeightInches: 36,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -4,
      harvestRelativeWeeks: null,
      plantsPerSqFt: 16,
      sqftColor: "#4B5320",
      permLayer: "VINE",
      isNitrogenFixer: true,
      isDynamicAccumulator: false,
      isEdible: false,
      attractsPollinators: true,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
    {
      name: "Oats",
      scientificName: "Avena sativa",
      variety: null,
      category: "COVER_CROP",
      lifecycle: "ANNUAL",
      sunRequirement: "FULL_SUN",
      waterNeed: "LOW",
      seasonType: "COOL",
      daysToMaturity: 60,
      daysToGermination: 7,
      spacingInches: 2,
      plantHeightInches: 36,
      startIndoorWeeks: null,
      transplantWeeks: null,
      directSowWeeks: -4,
      harvestRelativeWeeks: null,
      plantsPerSqFt: 16,
      sqftColor: "#9E9764",
      permLayer: "GROUND_COVER",
      isNitrogenFixer: false,
      isDynamicAccumulator: false,
      isEdible: true,
      attractsPollinators: false,
      deerResistant: false,
      dataSource: "SEED",
      isUserEdited: false,
    },
  ] as const

  const count = await prisma.plant.createMany({
    data: plants.map((p) => ({ ...p })),
  })

  console.log(`Seeded ${count.count} plants for Zone 3B`)
}
