import { type GenerateCalendar } from "wasp/server/operations"
import { type CalendarEvent } from "wasp/entities"
import { HttpError } from "wasp/server"
import { addWeeks, parse, format } from "date-fns"
import { requirePropertyMember } from "../lib/auth"

type GenerateCalendarArgs = {
  propertyId: string
  year: number
}

type EventDef = {
  plantId: string
  plantName: string
  eventType: string
  weeksFromLastFrost: number
  title: string
}

export const generateCalendar: GenerateCalendar<
  GenerateCalendarArgs,
  CalendarEvent[]
> = async (args, context) => {
  await requirePropertyMember(context, args.propertyId)

  const property = await context.entities.Property.findUnique({
    where: { id: args.propertyId },
  })
  if (!property) throw new HttpError(404, "Property not found")

  const lastFrostDate = parse(
    `${args.year}-${property.lastFrostDate}`,
    "yyyy-MM-dd",
    new Date()
  )

  const plants = await context.entities.Plant.findMany()

  // Build event definitions from plant schedule fields
  const eventDefs: EventDef[] = []

  for (const plant of plants) {
    if (plant.startIndoorWeeks != null) {
      eventDefs.push({
        plantId: plant.id,
        plantName: plant.name,
        eventType: "SEED_START_INDOOR",
        weeksFromLastFrost: -plant.startIndoorWeeks,
        title: `Start ${plant.name} indoors`,
      })
    }

    if (plant.transplantWeeks != null) {
      eventDefs.push({
        plantId: plant.id,
        plantName: plant.name,
        eventType: "TRANSPLANT",
        weeksFromLastFrost: plant.transplantWeeks,
        title: `Transplant ${plant.name}`,
      })
    }

    if (plant.directSowWeeks != null) {
      eventDefs.push({
        plantId: plant.id,
        plantName: plant.name,
        eventType: "SEED_START_OUTDOOR",
        weeksFromLastFrost: plant.directSowWeeks,
        title: `Direct sow ${plant.name}`,
      })
    }

    if (plant.harvestRelativeWeeks != null) {
      eventDefs.push({
        plantId: plant.id,
        plantName: plant.name,
        eventType: "HARVEST_START",
        weeksFromLastFrost: plant.harvestRelativeWeeks,
        title: `Harvest ${plant.name}`,
      })
    }
  }

  const results: CalendarEvent[] = []

  for (const def of eventDefs) {
    const eventDate = addWeeks(lastFrostDate, def.weeksFromLastFrost)
    const dateStr = format(eventDate, "yyyy-MM-dd")
    const generationKey = `${args.year}:${def.plantId}:${def.eventType}`

    // Check if event already exists
    const existing = await context.entities.CalendarEvent.findUnique({
      where: { generationKey },
    })

    if (existing) {
      // Skip user-edited events
      if (existing.isUserEdited) {
        results.push(existing)
        continue
      }

      // Update the existing auto-generated event
      const updated = await context.entities.CalendarEvent.update({
        where: { id: existing.id },
        data: {
          title: def.title,
          date: dateStr,
          eventType: def.eventType as any,
          plantId: def.plantId,
        },
      })
      results.push(updated)
    } else {
      // Create new event
      const created = await context.entities.CalendarEvent.create({
        data: {
          title: def.title,
          eventType: def.eventType as any,
          date: dateStr,
          allDay: true,
          autoGenerated: true,
          generationKey,
          propertyId: args.propertyId,
          plantId: def.plantId,
        },
      })
      results.push(created)
    }
  }

  return results
}
